# Use the official Ubuntu image as the base
FROM ghcr.io/hiconic-os/ci-base/main:latest

# Metadata as described above
LABEL maintainer="your-email@example.com"
LABEL version="1.0"
LABEL description="Hiconic CI/CD image based on Ubuntu with hiconic-sdk"

#############################
# Prepare Hiconic-SDK
#############################

COPY build/hiconic-sdk.zip /hiconic-sdk.zip

RUN unzip /hiconic-sdk.zip -d /

RUN rm /hiconic-sdk.zip

RUN ls -la /hiconic-sdk/tools/shared-lib

ENV DEVROCK_SDK_HOME=/hiconic-sdk
ENV HICONIC_SDK_HOME=/hiconic-sdk
ENV PATH=${PATH}:/hiconic-sdk/tools/jinni/bin

#############################
# Finalize
#############################

RUN rm -rf /var/lib/apt/lists/*

RUN echo $SHELL

# Set the default command for the container (this can be overridden)
SHELL ["/bin/bash", "-c"]

RUN echo $SHELL