# Use the official Ubuntu image as the base
FROM ubuntu:latest

# Metadata as described above
LABEL maintainer="your-email@example.com"
LABEL version="1.0"
LABEL description="Hiconic CI/CD base image based on Ubuntu"

#############################
# Install tools
#############################

RUN apt-get update

# Update and install basic tools and Java (OpenJDK)
RUN apt-get install -y \
#    openjdk-21-jdk \
    curl \
	docker.io \
    git \
    unzip \
    lftp \
    locales

#
# Set the locale to UTF-8
#

RUN locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

#
# Java 21
#

ENV JDK_DOWNLOAD_URL=https://cdn.azul.com/zulu/bin/zulu21.42.19-ca-jdk21.0.7-linux_x64.tar.gz
                     
RUN curl --fail --retry 3 --output archive.tar.gz --location ${JDK_DOWNLOAD_URL} && \
	mkdir -p /opt/java/jdk && \
	tar -C /opt/java/jdk --strip 1 -xvzf archive.tar.gz && \
	rm archive.tar.gz

ENV JAVA_HOME=/opt/java/jdk
ENV JAVA_OPTS=-Xmx4g
ENV PATH=${JAVA_HOME}/bin:${PATH}

#
# Java 8 for GWT
#

ENV JDK_8_DOWNLOAD_URL=https://cdn.azul.com/zulu/bin/zulu8.74.0.17-ca-jdk8.0.392-linux_x64.tar.gz

RUN curl --fail --retry 3 --output archive.tar.gz --location ${JDK_8_DOWNLOAD_URL} && \
	mkdir -p /opt/java/jdk8 && \
	tar -C /opt/java/jdk8 --strip 1 -xvzf archive.tar.gz && \
	rm archive.tar.gz

ENV JAVA_8_HOME=/opt/java/jdk8


#############################
# Finalize
#############################

# RUN rm -rf /var/lib/apt/lists/*

# Set the default command for the container (this can be overridden)

RUN echo $SHELL

CMD [ "bash" ]

RUN echo $SHELL

# Set the default command for the container (this can be overridden)
SHELL ["/bin/bash", "-c"]

RUN echo $SHELL

