# Use the official Ubuntu image as the base
FROM ghcr.io/hiconic-os/ci-base/main:latest AS before-prefetch

# Metadata as described above
LABEL maintainer="your-email@example.com"
LABEL version="1.0"
LABEL description="Hiconic CI/CD image based on Ubuntu with devrock-sdk"

#############################
# Prepare Devrock-SDK
#############################

# Copy myfile.txt from your machine to the /app directory in the container
COPY build/devrock-sdk.zip /devrock-sdk.zip

RUN unzip /devrock-sdk.zip -d /

RUN rm /devrock-sdk.zip

ENV DEVROCK_SDK_HOME=/devrock-sdk
ENV PATH=${PATH}:/devrock-sdk/tools/jinni/bin

#############################
# Prefetch gradle deps
#############################

FROM before-prefetch AS prefetch

ARG GITHUB_READ_PACKAGES_TOKEN

RUN mkdir /gradle-prefetch

COPY res/build.gradle /gradle-prefetch
COPY res/buildscript.gradle /gradle-prefetch

WORKDIR /gradle-prefetch

RUN dr tasks --no-daemon

#############################
# Finalize
#############################

FROM before-prefetch

COPY --from=prefetch /root/.gradle /root/.gradle

RUN rm -rf /var/lib/apt/lists/*

RUN echo $SHELL

# Set the default command for the container (this can be overridden)
SHELL ["/bin/bash", "-c"]

RUN echo $SHELL