name: Build Image - Base

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ghcr.io/hiconic-os/ci-base/${{ github.ref_name }}:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Packages
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: gradle buildBaseImage
    
      - name: Push Docker image
        run: docker push ${{ env.IMAGE_TAG }}