name: Build Image - Devrock SDK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ghcr.io/hiconic-os/ci-devrock-sdk/${{ github.ref_name }}:latest

      OPENTF_REPO_USER: ${{ secrets.OPENTF_REPO_USER }}
      OPENTF_REPO_PASSWORD: ${{ secrets.OPENTF_REPO_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Packages
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Download Devrock SDK
        run: gradle downloadDevrockSdk

      - name: Build Docker image
        run: gradle buildDevrockImage
    
      - name: Push Docker image
        run: docker push ${{ env.IMAGE_TAG }}