name: Restore Image - Hiconic SDK

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_LATEST_TAG: ghcr.io/hiconic-os/ci-hiconic-sdk/${{ github.ref_name }}:latest
      IMAGE_SNAPSHOT_TAG: ghcr.io/hiconic-os/ci-hiconic-sdk-snapshot/${{ github.ref_name }}:${{ inputs.version }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Packages
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Backup Hiconic SDK Image
        run: docker pull ${{ env.IMAGE_SNAPSHOT_TAG }}

      - name: Push Docker Image as Latest
        run: |
          docker tag ${{ env.IMAGE_SNAPSHOT_TAG }} ${{ env.IMAGE_LATEST_TAG }}
          docker push ${{ env.IMAGE_LATEST_TAG }}