name: Build Image - Runtime

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_LATEST_TAG: ghcr.io/hiconic-os/runtime-base:latest
      IMAGE_SNAPSHOT_TAG: ghcr.io/hiconic-os/runtime-base:${{ github.run_number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Packages
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.IMAGE_LATEST_TAG }} -f Dockerfile-runtime .

      - name: Push Docker Image
        run: docker push ${{ env.IMAGE_LATEST_TAG }}

      - name: Push Backup Docker Image
        run: |
          docker tag ${{ env.IMAGE_LATEST_TAG }} ${{ env.IMAGE_SNAPSHOT_TAG }}
          docker push ${{ env.IMAGE_SNAPSHOT_TAG }}